import { standardCollectors, macroCollectors } from './src/standard-collectors.js';
import { ALL_MODULES, MACRO_MODULES } from './src/simulation-autowired.js';
console.log('timeseries', standardCollectors.timeseries.length, 'macro ts', macroCollectors.timeseries.length);
console.log('metrics', standardCollectors.metrics?.length, 'macro metrics', macroCollectors.metrics?.length);
console.log('modules', ALL_MODULES.length, MACRO_MODULES.length);
const t0 = process.hrtime.bigint();
standardCollectors.timeseries.filter(e=>e.module==='generations');
standardCollectors.metrics?.filter(e=>e.source===undefined);
ALL_MODULES.filter(m=>m.name==='x');
const t1 = process.hrtime.bigint();
console.log('filter trio ns', Number(t1-t0));
