/**
 * Production Module
 *
 * Biophysical production function where GDP emerges from energy, capital, and labor.
 * Based on Ayres-Warr (2009) finding that useful energy is the dominant growth driver.
 *
 * Core equation (normalized Cobb-Douglas):
 *   GDP = Y₀ × (K/K₀)^α × (L/L₀)^β × (E/E₀)^γ × efficiency × (1 - damages)
 *
 * Efficiency replaces exogenous TFP with two physical factors:
 *   1. End-use efficiency: an effective (uncapped) service-productivity index coupled to demand's intensity decline, structural component decaying post-2025
 *   2. Organizational efficiency (education-driven, diminishing returns)
 *
 * Ayres-Warr elasticities:
 *   α = 0.25 (capital)
 *   β = 0.15 (labor)
 *   γ = 0.55 (useful energy)
 *
 * All inputs are lagged (from previous year), so production runs early in the
 * step order (after demographics). This breaks the GDP→demand→dispatch→energy→GDP
 * cycle cleanly.
 *
 * Sources:
 * - Ayres & Warr (2009): The Economic Growth Engine
 * - Kümmel et al. (2010): LINEX production function
 * - Santos et al. (2018): Exergy economics survey
 * - Brockway et al. (2018): Exergy-GDP relationship
 */

import { defineModule, Module, ValidationResult, validatedMerge, unitConnector } from 'tsimulation';
import { STRUCTURAL_ANCHOR_YEAR } from '../primitives/math.js';

// =============================================================================
// PARAMETERS
// =============================================================================

export interface ProductionParams {
  alpha: number;              // Capital elasticity (0.25)
  beta: number;               // Labor elasticity (0.15)
  gamma: number;              // Useful energy elasticity (0.55)
  initialGDP: number;         // $T (2025 global GDP)
  electricExergy: number;     // Exergy factor for electricity (0.95)
  thermalExergy: number;      // Exergy factor for direct fuel use (0.35)
  foodStressElasticity: number; // GDP reduction per unit food stress (0.3)

  // Effective service-efficiency index: single coupled series with demand's
  // autonomous intensity decline (see methodology note in the defaults)
  endUseEfficiency0: number;        // η₀: effective productivity index at run start (0.23)
  serviceEfficiencyGrowth: number;  // near-term η growth rate/yr = GDP-weighted demand intensityDecline (0.0129)
  structuralEfficiencyShare: number;      // fraction of serviceEfficiencyGrowth that is decaying structural change (rest is persistent device efficiency)
  structuralDecayHalfLife: number;        // years for the structural component to halve post-2025 (0 = no decay)

  // Organizational efficiency (education-driven)
  orgEfficiencySensitivity: number;    // φ: sensitivity to college share gain (0.35)
  orgEfficiencyMaxCollegeGain: number; // max college share improvement (0.40)

  // Automation payoff: robots/AI augment effective labor — the only channel
  // by which automation affects output (its electricity is subtracted from
  // E as intermediate consumption).
  robotLaborEquivalent: number;     // worker-equivalents per robot (Acemoglu & Restrepo 2020 find 1 robot displaces ~3-6 workers; output equivalent lower)
  aiWorkerEquivalentPerTWh: number; // worker-equivalents per TWh/yr of datacenter compute

  /** Calendar-year physical fuel shocks generated by a monthly submodel. */
  energySupplyShocks: readonly AnnualEnergySupplyShock[];
}

export interface AnnualEnergySupplyShock {
  year: number;
  /** Fraction of otherwise available non-electric energy physically supplied. */
  nonElectricAvailability: number;
}

export const productionDefaults: ProductionParams = {
  alpha: 0.25,
  beta: 0.15,
  gamma: 0.55,
  initialGDP: 158,            // $158T PPP (2025 global GDP, 2017 intl $)
  electricExergy: 0.95,       // Electricity is nearly pure useful work
  thermalExergy: 0.35,        // Thermal fuels ~35% exergy efficiency
  foodStressElasticity: 0.3,  // 30% GDP hit at full food stress
  // Effective service-efficiency index: growth coupled to the demand
  // module's autonomous intensity decline (one parameter, two views; the
  // pin in simulation.test.ts asserts this default equals demand's
  // gdpWeightedIntensityDecline()). METHODOLOGY NOTE (calibration review):
  // this 1.29%/yr BUNDLES two service-preserving components — measured
  // device (second-law) efficiency, ~0.85-0.9%/yr in the CL-PFU database
  // (Brockway group: world 15% in 1971 -> 23% in 2020), plus
  // value-preserving structural change (~0.4%/yr residual: sectoral shift
  // produces the same GDP from fewer energy services). eta here is
  // therefore an effective index, not the measured second-law efficiency;
  // that 0.15 x 1.0129^35 = 0.235 lands on Brockway's measured 2020s level
  // is a consistency check on the bundle (the structural component roughly
  // offsets starting from 1990's measured ~0.18 rather than 0.15), not an
  // identity.
  endUseEfficiency0: 0.23,          // effective index 2025; numerically in Brockway et al.'s measured ~0.20-0.25 band (see methodology note above)
  serviceEfficiencyGrowth: 0.0129,  // GDP-weighted average of demand regional intensityDecline defaults (IEA Energy Efficiency 2024 history)
  // The 1.29%/yr near-term rate does not persist 75 years: ~1/3 of it is
  // structural change (sectoral shift toward services, China/India catch-up)
  // that matures and decays post-2025, while the ~0.87%/yr measured device
  // component persists. Without this forward decay the baseline compounded to
  // ~$1.4Q by 2100 — above the SSP5 marker while labeled "no policy." The
  // 1990-2025 backcast is unaffected (decay is anchored at 2025; pre-2025
  // years keep the full historical rate — structural change was strong then).
  // Both parameters below are a JUDGMENT split of a soft residual, not
  // independently sourced: the 1.29%/yr near-term rate is decomposed into a
  // ~0.87%/yr persistent device component (the CL-PFU measured rate) and the
  // ~0.42%/yr remainder attributed to transitional structural change. The
  // share (0.33) and half-life (18yr) are chosen so the structural bonus is
  // mostly spent by ~2050-2060 (consistent with China/India intensity
  // convergence maturing mid-century), NOT calibrated to a specific study.
  // This is the dominant GDP-level lever's least-pinned degree of freedom —
  // see docs/SENSITIVITY.md; treat GDP 2100 as a band, not a point.
  structuralEfficiencyShare: 0.33,  // ~0.42 of 1.29 pp/yr is structural (bonus over the CL-PFU device rate)
  structuralDecayHalfLife: 18,      // structural component halves ~every 18yr post-2025 (judgment, not sourced)
  orgEfficiencySensitivity: 0.35,
  orgEfficiencyMaxCollegeGain: 0.40,
  robotLaborEquivalent: 2,      // worker-equivalents per robot: Acemoglu & Restrepo (2020) find 1 robot displaces ~3-6 workers; 2 is a conservative output-equivalent. This is now the ONLY channel robots affect output (their energy is subtracted from E).
  aiWorkerEquivalentPerTWh: 0,  // no literature referent for an output equivalent; datacenter services' value is embedded in the measured GDP of the sectors buying them, so 0 is the conservative default — the ai-energy-boom scenario explores >0
  energySupplyShocks: [],
};

// =============================================================================
// STATE
// =============================================================================

export interface ProductionState {
  initialCapital: number;       // K₀, captured in year 0
  initialLabor: number;         // L₀, captured in year 0
  initialUsefulEnergy: number;  // E₀, captured in year 0
  initialCollegeShare: number;  // Captured in year 0
  initialDamageFactor: number;  // Combined damage factor at anchor, captured in year 0
}

// =============================================================================
// INPUTS / OUTPUTS
// =============================================================================

export interface ProductionInputs {
  /** Capital stock $T (from capital, lagged) */
  capitalStock: number;
  /** Effective workers (from demographics, current year) */
  effectiveWorkers: number;
  /** Total electricity generation TWh (from dispatch, lagged) */
  totalGeneration: number;
  /** Non-electric energy TWh (from demand, lagged) */
  nonElectricEnergy: number;
  /** Climate damage fraction 0-1 (from climate, lagged) */
  damages: number;
  /** Energy burden damage fraction 0-1 (from demand, lagged) */
  energyBurdenDamage: number;
  /** Food stress fraction 0-1 (from resources, lagged) */
  foodStress: number;
  /** Resource energy consumption TWh (from resources, lagged) */
  resourceEnergy: number;
  /** Energy system overhead TWh — embodied + operating (from energy, lagged) */
  energySystemOverhead: number;
  /** College share fraction (from demographics, current year) */
  collegeShare: number;
  /** CDR energy consumption TWh (from cdr, lagged) */
  cdrEnergy: number;
  /** Robots per 1000 workers (from demand, lagged); optional for standalone use */
  robotsPer1000?: number;
  /** Robot fleet electricity TWh (from demand, lagged); optional for standalone use */
  robotLoadTWh?: number;
  /** Datacenter compute load TWh (from demand, lagged); optional for standalone use */
  dataCenterLoadTWh?: number;
}

export interface ProductionOutputs {
  /** GDP from biophysical production function ($T) */
  gdp: number;
  /** Exergy-weighted useful energy (TWh) */
  productionUsefulEnergy: number;
  /** (K/K₀)^α */
  capitalContribution: number;
  /** (L/L₀)^β */
  laborContribution: number;
  /** (E/E₀)^γ */
  energyContribution: number;
  /** Combined efficiency multiplier (replaces TFP) */
  efficiencyLevel: number;
  /** Current effective service-efficiency index η(t) */
  eta: number;
}

// =============================================================================
// MODULE DEFINITION
// =============================================================================

export const productionModule: Module<
  ProductionParams,
  ProductionState,
  ProductionInputs,
  ProductionOutputs
> = defineModule<ProductionParams, ProductionState, ProductionInputs, ProductionOutputs>({
  name: 'production',
  description: 'Biophysical production function (Ayres-Warr): GDP from energy, capital, labor',

  defaults: productionDefaults,

  paramMeta: {
    alpha: {
      description: 'Capital elasticity in production function (Ayres-Warr). Traditional Solow uses ~0.33, biophysical model uses 0.25.',
      unit: 'fraction',
      range: { min: 0.10, max: 0.40, default: 0.25 },
      tier: 1 as const,
    },
    beta: {
      description: 'Labor elasticity in production function. Low because much "labor" growth is really energy-augmented.',
      unit: 'fraction',
      range: { min: 0.05, max: 0.30, default: 0.15 },
      tier: 1 as const,
    },
    gamma: {
      description: 'Useful energy elasticity. Ayres-Warr find ~0.5-0.6 for useful work (dominant growth driver); mainstream cost-share logic implies ~0.05-0.08. GDP levels are highly sensitive to this choice — see docs/SENSITIVITY.md.',
      unit: 'fraction',
      range: { min: 0.05, max: 0.70, default: 0.55 },
      tier: 1 as const,
    },
    serviceEfficiencyGrowth: {
      description: 'Near-term growth rate of the effective service-efficiency index (= demand GDP-weighted intensity decline; coupled at runtime). THE dominant GDP-level dial: after the allocator and DC-capex corrections a +/-40% sweep spans roughly $0.5Q-$7.9Q in 2100, exposing an uncalibrated growth loop. Structural share decays post-2025. See docs/SENSITIVITY.md.',
      unit: 'fraction/year',
      range: { min: 0.005, max: 0.03, default: 0.0129 },
      tier: 1 as const,
    },
    robotLaborEquivalent: {
      description: 'Worker-equivalents each robot adds to effective labor — the ONLY channel robots affect output (their electricity is subtracted from productive useful energy as intermediate consumption). Default 2: Acemoglu & Restrepo (2020) find one industrial robot displaces ~3-6 workers; 2 is a conservative output-equivalent. 0 makes robots a pure parasitic load.',
      unit: 'worker-equivalents/robot',
      range: { min: 0, max: 20, default: 2 },
      tier: 1 as const,
    },
    aiWorkerEquivalentPerTWh: {
      description: 'Cognitive worker-equivalents per TWh/yr of datacenter compute added to effective labor. 0 = compute is a pure energy sink (calibrated baseline). Magnitude anchor: 1e5 means today\'s ~500 TWh of datacenter load augments ~50M workers (~1% of the global workforce) — the ai-energy-boom scenario value. 1e6 would mean today\'s compute already matches ~10% of the workforce.',
      unit: 'worker-equivalents/TWh',
      range: { min: 0, max: 1e7, default: 0 },
      tier: 1 as const,
    },
  },

  inputs: [
    'capitalStock',
    'effectiveWorkers',
    'totalGeneration',
    'nonElectricEnergy',
    'damages',
    'energyBurdenDamage',
    'foodStress',
    'resourceEnergy',
    'energySystemOverhead',
    'collegeShare',
    'cdrEnergy',
    'robotsPer1000',
    'robotLoadTWh',
    'dataCenterLoadTWh',
  ] as const,

  outputs: [
    'gdp',
    'productionUsefulEnergy',
    'capitalContribution',
    'laborContribution',
    'energyContribution',
    'efficiencyLevel',
    'eta',
  ] as const,

  connectorTypes: {
    inputs: {
      capitalStock: unitConnector('number', '$T'),
      effectiveWorkers: unitConnector('number', 'people'),
      totalGeneration: unitConnector('number', 'TWh/year'),
      nonElectricEnergy: unitConnector('number', 'TWh/year'),
      damages: unitConnector('number', 'fraction'),
      energyBurdenDamage: unitConnector('number', 'fraction'),
      foodStress: unitConnector('number', 'fraction'),
      resourceEnergy: unitConnector('number', 'TWh/year'),
      energySystemOverhead: unitConnector('number', 'TWh/year'),
      collegeShare: unitConnector('number', 'fraction'),
      cdrEnergy: unitConnector('number', 'TWh/year'),
      robotsPer1000: unitConnector('number', 'robot/kpeople'),
      robotLoadTWh: unitConnector('number', 'TWh/year'),
      dataCenterLoadTWh: unitConnector('number', 'TWh/year'),
    },
    outputs: {
      gdp: unitConnector('number', '$T/year'),
      productionUsefulEnergy: unitConnector('number', 'TWh/year'),
      capitalContribution: unitConnector('number', '1'),
      laborContribution: unitConnector('number', '1'),
      energyContribution: unitConnector('number', '1'),
      efficiencyLevel: unitConnector('number', '1'),
      eta: unitConnector('number', '1'),
    },
  },

  validate(params: Partial<ProductionParams>): ValidationResult {
    const errors: string[] = [];
    const warnings: string[] = [];

    if (params.alpha !== undefined && (params.alpha < 0 || params.alpha > 1)) {
      errors.push('alpha must be between 0 and 1');
    }
    if (params.beta !== undefined && (params.beta < 0 || params.beta > 1)) {
      errors.push('beta must be between 0 and 1');
    }
    if (params.gamma !== undefined && (params.gamma < 0 || params.gamma > 1)) {
      errors.push('gamma must be between 0 and 1');
    }
    if (params.alpha !== undefined && params.beta !== undefined && params.gamma !== undefined) {
      const sum = params.alpha + params.beta + params.gamma;
      if (sum > 1.1) {
        warnings.push(`α+β+γ = ${sum.toFixed(2)}, strongly increasing returns to scale`);
      }
    }
    if (params.initialGDP !== undefined && params.initialGDP <= 0) {
      errors.push('initialGDP must be positive');
    }
    if (params.serviceEfficiencyGrowth !== undefined &&
        (params.serviceEfficiencyGrowth < 0 || params.serviceEfficiencyGrowth > 0.04)) {
      errors.push('serviceEfficiencyGrowth must be between 0 and 4%/year');
    }
    if (params.structuralEfficiencyShare !== undefined &&
        (params.structuralEfficiencyShare < 0 || params.structuralEfficiencyShare > 1)) {
      errors.push('structuralEfficiencyShare must be between 0 and 1');
    }
    if (params.structuralDecayHalfLife !== undefined && params.structuralDecayHalfLife < 0) {
      errors.push('structuralDecayHalfLife must be non-negative (0 = no decay)');
    }

    if (params.robotLaborEquivalent !== undefined &&
        (params.robotLaborEquivalent < 0 || params.robotLaborEquivalent > 20)) {
      errors.push('robotLaborEquivalent must be between 0 and 20 worker-equivalents per robot');
    }
    if (params.aiWorkerEquivalentPerTWh !== undefined &&
        (params.aiWorkerEquivalentPerTWh < 0 || params.aiWorkerEquivalentPerTWh > 1e7)) {
      errors.push('aiWorkerEquivalentPerTWh must be between 0 and 1e7 worker-equivalents per TWh');
    }
    for (const shock of params.energySupplyShocks ?? []) {
      if (!Number.isInteger(shock.year)) {
        errors.push('energySupplyShocks year must be an integer');
      }
      if (shock.nonElectricAvailability < 0 || shock.nonElectricAvailability > 1) {
        errors.push('energySupplyShocks nonElectricAvailability must be between 0 and 1');
      }
    }

    return { valid: errors.length === 0, errors, warnings };
  },

  mergeParams(partial: Partial<ProductionParams>): ProductionParams {
    return validatedMerge('production', this.validate, (p) => ({
      ...productionDefaults,
      ...p,
    }), partial);
  },

  init(_params: ProductionParams): ProductionState {
    return {
      initialCapital: 0,
      initialLabor: 0,
      initialUsefulEnergy: 0,
      initialCollegeShare: 0,
      initialDamageFactor: 1,
    };
  },

  step(state, inputs, params, year, yearIndex) {
    const {
      capitalStock,
      effectiveWorkers,
      totalGeneration,
      nonElectricEnergy,
      damages,
      energyBurdenDamage,
      foodStress,
      resourceEnergy,
      energySystemOverhead,
      collegeShare,
      cdrEnergy,
    } = inputs;

    // Compute useful energy from lagged supply (exergy-weighted)
    // Subtract energy consumed by the system itself (not available for productive GDP):
    //   - resourceEnergy: mining + farming operations
    //   - energySystemOverhead: embodied energy of new capacity + operating energy
    //   - cdrEnergy: carbon removal
    //   - robot/datacenter loads: automation is INTERMEDIATE consumption —
    //     its output enters solely through the labor-augmentation terms
    //     below. Counting its electricity in E as well was a
    //     perpetual-motion channel (any pure consumption load raised GDP
    //     through E^gamma) and, with the payoff on, double counting.
    const energySupplyShock = params.energySupplyShocks.find(
      (shock) => shock.year === year,
    );
    const nonElectricAvailability = Math.max(
      0,
      Math.min(1, energySupplyShock?.nonElectricAvailability ?? 1),
    );
    const grossUsefulEnergy = totalGeneration * params.electricExergy
      + nonElectricEnergy * nonElectricAvailability * params.thermalExergy;
    // Assumption: overhead is roughly half electric (0.95) / half thermal
    // (0.35) exergy, giving ~0.65 — no direct source
    const OVERHEAD_EXERGY = 0.65;
    const automationEnergy = (inputs.robotLoadTWh ?? 0) + (inputs.dataCenterLoadTWh ?? 0);
    const systemOverhead = resourceEnergy * params.thermalExergy
      + energySystemOverhead * OVERHEAD_EXERGY
      + (cdrEnergy + automationEnergy) * params.electricExergy; // CDR + automation are purely electric
    const productionUsefulEnergy = Math.max(0, grossUsefulEnergy - systemOverhead);

    // Automation-augmented labor: robots add physical worker-equivalents,
    // datacenter compute adds cognitive worker-equivalents. The year-0
    // anchor captures the augmented value, so only relative growth in
    // automation moves GDP, not its 2025 level.
    const robotsPer1000 = inputs.robotsPer1000 ?? 0;
    const dataCenterLoadTWh = inputs.dataCenterLoadTWh ?? 0;
    const augmentedWorkers = effectiveWorkers
      * (1 + params.robotLaborEquivalent * robotsPer1000 / 1000)
      + params.aiWorkerEquivalentPerTWh * dataCenterLoadTWh;

    // Year 0: capture initial values for normalization
    let initialCapital = state.initialCapital;
    let initialLabor = state.initialLabor;
    let initialUsefulEnergy = state.initialUsefulEnergy;
    let initialCollegeShare = state.initialCollegeShare;

    if (yearIndex === 0) {
      initialCapital = capitalStock;
      initialLabor = augmentedWorkers;
      initialUsefulEnergy = productionUsefulEnergy;
      initialCollegeShare = collegeShare;
    }

    // Guard against zero division
    const safeK0 = initialCapital > 0 ? initialCapital : 1;
    const safeL0 = initialLabor > 0 ? initialLabor : 1;
    const safeE0 = initialUsefulEnergy > 0 ? initialUsefulEnergy : 1;

    // Production function components (normalized)
    const capitalContribution = Math.pow(capitalStock / safeK0, params.alpha);
    const laborContribution = Math.pow(augmentedWorkers / safeL0, params.beta);
    const energyContribution = Math.pow(Math.max(0.01, productionUsefulEnergy / safeE0), params.gamma);

    // =========================================================================
    // Endogenous efficiency (replaces exogenous TFP)
    // =========================================================================

    // 1. End-use efficiency: coupled to the demand module's autonomous
    //    intensity decline — the SAME physical improvements (motors, LEDs,
    //    heat pumps, industrial processes) that cut final energy per service
    //    on the demand side raise useful work per final energy here. Without
    //    this coupling, intensity decline was a pure GDP destroyer: demand
    //    removed the energy while production booked it as lost input
    //    (GDP ~ Intensity^1.2 through the gamma loop).
    // Cumulative log-efficiency growth from the run's anchor year to `year`,
    // with the structural component decaying in CALENDAR time past 2025 (so
    // the 1990-anchored backcast, which ends at 2025, keeps the full rate
    // throughout and its pin is unchanged, while the 2025-anchored forward
    // run sees the structural bonus fade). rate(s) = g x [(1-share) +
    // share x 0.5^(max(0,s-2025)/halfLife)].
    const anchorYear = year - yearIndex;
    const g = params.serviceEfficiencyGrowth;
    const share = params.structuralEfficiencyShare;
    const hl = params.structuralDecayHalfLife;
    const flatYears = Math.max(0, Math.min(year, STRUCTURAL_ANCHOR_YEAR) - anchorYear);   // pre-anchor: full structural bonus
    const decayYears = Math.max(0, year - Math.max(anchorYear, STRUCTURAL_ANCHOR_YEAR));  // post-anchor: decaying
    const decayIntegral = hl > 0
      ? (hl / Math.LN2) * (1 - Math.pow(0.5, decayYears / hl))
      : decayYears;
    const cumLogGrowth = g * ((1 - share) * yearIndex + share * (flatYears + decayIntegral));
    // No hard cap: eta is an EFFECTIVE productivity index (bundles uncapped
    // structural change), not a thermodynamic efficiency. A finite cap
    // re-split the coupled series above it (demand keeps stripping energy
    // while eta freezes -> GDP collapses at high efficiencyMultiplier); the
    // structural decay bounds growth without a cliff. For realistic
    // multipliers (<=1.5) eta stays ~0.71, well within the device ~0.60-0.90
    // second-law range; only implausible (>2x) efficiency pushes it past 1.
    const eta = params.endUseEfficiency0 * Math.exp(cumLogGrowth);
    const endUseEfficiency = eta / params.endUseEfficiency0;

    // 2. Organizational efficiency (education-driven, diminishing returns)
    //    Better-educated workforce coordinates more efficiently.
    //    Easy organizational improvements captured first → diminishing returns.
    const collegeDelta = Math.max(0, collegeShare - initialCollegeShare);
    const diminishing = Math.max(0, 1 - collegeDelta / params.orgEfficiencyMaxCollegeGain);
    const organizationalEfficiency = 1 + params.orgEfficiencySensitivity * collegeDelta * diminishing;

    // Combined efficiency level
    const efficiencyLevel = endUseEfficiency * organizationalEfficiency;

    // Damage factors, normalized to the anchor year like every other input:
    // observed 2025 GDP already includes 2025's prevailing damages, so only
    // CHANGES in damages relative to the anchor move GDP. (With bootstrapped
    // lags, year 0 sees real 2025 damages rather than zero.)
    const damageFactor = 1 - damages;
    const burdenFactor = 1 - energyBurdenDamage;
    const foodFactor = 1 - params.foodStressElasticity * Math.max(0, Math.min(1, foodStress));
    const combinedDamageFactor = damageFactor * burdenFactor * foodFactor;
    let initialDamageFactor = state.initialDamageFactor;
    if (yearIndex === 0) {
      initialDamageFactor = combinedDamageFactor > 0 ? combinedDamageFactor : 1;
    }
    const relativeDamageFactor = combinedDamageFactor / initialDamageFactor;

    // GDP = Y₀ × (K/K₀)^α × (L/L₀)^β × (E/E₀)^γ × efficiency × damage factors
    const gdp = params.initialGDP
      * capitalContribution
      * laborContribution
      * energyContribution
      * efficiencyLevel
      * relativeDamageFactor;

    return {
      state: {
        initialCapital,
        initialLabor,
        initialUsefulEnergy,
        initialCollegeShare,
        initialDamageFactor,
      },
      outputs: {
        gdp,
        productionUsefulEnergy,
        capitalContribution,
        laborContribution,
        energyContribution,
        efficiencyLevel,
        eta,
      },
    };
  },
});
