/**
 * Growth backcast 1990-2025: can the production function retrodict history?
 *
 * Drives the ACTUAL production module (src/modules/production.ts) — same
 * exergy weighting, same endogenous efficiency, no exogenous TFP — with
 * observed world inputs 1990-2025, anchored in 1990, and compares the
 * predicted GDP path to observed GDP. Also documents the calibration this
 * backcast forces, and checks the demand side's energy-GDP relationship
 * against the same window.
 *
 * Data and the backcast runner live in src/historical-backcast.ts (shared
 * with the calibration-pinning test in production.test.ts).
 *
 * Regenerates scripts/growth-backcast.md.
 */

import { writeFileSync } from 'fs';
import { runGrowthBackcast, ETA_1990, HISTORY_1990 } from '../src/historical-backcast.js';
import { productionDefaults } from '../src/modules/production.js';
import { demandModule } from '../src/modules/demand.js';
import { REGIONS } from '../src/domain-types.js';
import { runSimulation } from '../src/index.js';

const cagr = (a: number, b: number, years: number) => Math.log(b / a) / years;
const pct = (x: number) => (x * 100).toFixed(2);

// ---------------------------------------------------------------------------
// Backcast under current defaults, plus a γ sweep and the legacy miscalibration
// ---------------------------------------------------------------------------

const def = runGrowthBackcast();
const N = def.gdpPath.length;
const obsCagr = cagr(def.gdpObserved[0], def.gdpObserved[N - 1], N - 1);
const defCagr = cagr(def.gdpPath[0], def.gdpPath[N - 1], N - 1);

const gammaGrid = [0.08, 0.25, 0.40, 0.55, 0.70];
const gammaRuns = gammaGrid.map((g) => ({ g, r: runGrowthBackcast({ gamma: g }) }));

// The pre-calibration parameterization (unsourced η₀=0.35, guessed λ=0.25)
const legacy = runGrowthBackcast({
  endUseEfficiency0: 0.35,
  endUseLearningExponent: 0.25,
});

// ---------------------------------------------------------------------------
// Demand-side check: energy-GDP relationship over the same window
// ---------------------------------------------------------------------------

const gdpObs = def.gdpObserved;
const tfcObs = def.series.totalFinal;
const gTfc = cagr(tfcObs[0], tfcObs[N - 1], N - 1);
// Model's demand structure: final energy ≈ GDP × intensity, intensity
// declining at the GDP-weighted regional average of the demand defaults
// (computed here so the report tracks recalibrations automatically).
const observedIntensityDecline = obsCagr - gTfc;
const observedElasticity = gTfc / obsCagr;
const demandDefaults = demandModule.mergeParams({});
let intensityWeighted = 0;
let gdpWeight = 0;
for (const region of REGIONS) {
  const r = demandDefaults.regions[region];
  intensityWeighted += r.gdp2025 * r.intensityDecline;
  gdpWeight += r.gdp2025;
}
const MODEL_INTENSITY_DECLINE = intensityWeighted / gdpWeight;

// ---------------------------------------------------------------------------
// Forward contrast
// ---------------------------------------------------------------------------

const fwd: any = runSimulation();
const f = (y: number) => fwd.results[y - 2025];
const fwdE = (row: any) => row.productionUsefulEnergy;
// Exergy weighting for the historical series, using the model's own factors
const exergyE = (electricity: number, nonElectric: number) =>
  productionDefaults.electricExergy * electricity + productionDefaults.thermalExergy * nonElectric;

// ---------------------------------------------------------------------------
// Report
// ---------------------------------------------------------------------------

const lines: string[] = [];
const p = (s = '') => lines.push(s);

p('# Growth backcast 1990-2025');
p();
p('Generated by `scripts/growth-backcast.ts`. The forward production');
p('structure (exergy-weighted energy, endogenous Wright’s-law + education');
p('efficiency, no exogenous TFP) is anchored in 1990 and driven with');
p('observed world capital, labor, electricity, final energy, and education');
p('through 2025 (data + runner: `src/historical-backcast.ts`).');
p();

p('## Headline (current calibrated defaults)');
p();
p('| | 1990→2025 CAGR | GDP 2025 (1990=$47.6T) |');
p('|---|---:|---:|');
p(`| Observed (WDI) | ${pct(obsCagr)}%/yr | $${gdpObs[N - 1].toFixed(0)}T |`);
p(`| Model backcast | ${pct(defCagr)}%/yr | $${def.gdpPath[N - 1].toFixed(0)}T |`);
p();

p('## Calibration this backcast forces');
p();
p('The original efficiency parameterization (η₀=0.35, unsourced; λ=0.25,');
p('guessed) under-predicted history by a steady ~0.6-0.9 pp/yr — a missing');
p(`multiplicative residual (backcast 2025 GDP: $${legacy.gdpPath[N - 1].toFixed(0)}T, ` +
  `${(100 * (1 - legacy.gdpPath[N - 1] / gdpObs[N - 1])).toFixed(0)}% under observed).`);
p('η₀=0.35 claimed 1990’s efficiency was already near the 0.60 ceiling,');
p('strangling the learning headroom. The exergy-economics literature');
p('measures world second-law efficiency far lower. Recalibration:');
p();
p(`- **η(1990) = ${ETA_1990}** — De Stercke (2014) world exergy efficiency`);
p(`- **η_max = ${productionDefaults.endUseEfficiencyMax}** — Cullen & Allwood (2010) practical potential`);
p(`- **λ = ${productionDefaults.endUseLearningExponent}** — solved so the 1990-anchored backcast reproduces observed 2025 GDP`);
p(`- **Implied η(2025) = ${def.final.eta.toFixed(3)}** — inside Brockway et al. (2018)’s measured ~0.20-0.25, an`);
p('  independent check the solver was not fitted to');
p(`- **Forward cumulativeWorkHistory = ${productionDefaults.cumulativeWorkHistory}** — the 1990 base (${HISTORY_1990}yr) plus observed`);
p('  1990-2024 useful work expressed in 2025 units, so the forward run sits');
p('  at the correct point of the same learning curve');
p();
p('Three independent anchors (1990 level, 2025 level, 35-year growth path)');
p('are mutually consistent — the calibration is over-identified, not fitted.');
p('Pinned in `production.test.ts`.');
p();

p('## Factor decomposition at calibrated defaults (2025 level, 1990 = 1)');
p();
p('| Factor | Level ratio | Growth contribution (pp/yr) |');
p('|---|---:|---:|');
const c = def.final;
p(`| Capital (K/K₀)^${productionDefaults.alpha} | ${c.capitalContribution.toFixed(2)} | ${pct(Math.log(c.capitalContribution) / (N - 1))} |`);
p(`| Labor (L/L₀)^${productionDefaults.beta} | ${c.laborContribution.toFixed(2)} | ${pct(Math.log(c.laborContribution) / (N - 1))} |`);
p(`| Useful energy (E/E₀)^${productionDefaults.gamma} | ${c.energyContribution.toFixed(2)} | ${pct(Math.log(c.energyContribution) / (N - 1))} |`);
p(`| Endogenous efficiency | ${c.efficiencyLevel.toFixed(2)} | ${pct(Math.log(c.efficiencyLevel) / (N - 1))} |`);
p(`| **Model total** | ${(def.gdpPath[N - 1] / def.gdpPath[0]).toFixed(2)} | **${pct(defCagr)}** |`);
p(`| Observed | ${(gdpObs[N - 1] / gdpObs[0]).toFixed(2)} | ${pct(obsCagr)} |`);
p();

p('## γ sweep (with calibrated efficiency)');
p();
p('| γ | Predicted CAGR | Gap vs observed |');
p('|---|---:|---:|');
for (const { g, r } of gammaRuns) {
  const pc = cagr(r.gdpPath[0], r.gdpPath[N - 1], N - 1);
  p(`| ${g.toFixed(2)}${g === productionDefaults.gamma ? ' (default)' : ''} | ${pct(pc)}%/yr | ${pct(obsCagr - pc)} pp/yr |`);
}
p();
p('λ was solved at the default γ, so the default row closes by');
p('construction; the sweep shows how sharply the fit selects γ. Lower γ');
p('re-opens a large gap that efficiency calibration alone cannot close');
p('(λ would have to push η(2025) far above the measured Brockway range).');
p('History prefers the heterodox γ once efficiency levels are anchored to');
p('the exergy literature.');
p();

p('## Per-decade check (calibrated defaults)');
p();
p('| Period | Observed %/yr | Model %/yr | Gap pp/yr |');
p('|---|---:|---:|---:|');
for (let i = 0; i < N - 1; i += 10) {
  const j = Math.min(i + 10, N - 1);
  const o = cagr(gdpObs[i], gdpObs[j], j - i);
  const m = cagr(def.gdpPath[i], def.gdpPath[j], j - i);
  p(`| ${1990 + i}-${1990 + j} | ${pct(o)} | ${pct(m)} | ${pct(o - m)} |`);
}
p();

p('## Demand-side check: the energy-GDP relationship');
p();
p('The demand module ties energy services to GDP (unit income elasticity)');
p('minus autonomous intensity decline. Observed 1990-2025:');
p();
p(`- GDP ${pct(obsCagr)}%/yr, final energy ${pct(gTfc)}%/yr → observed intensity`);
p(`  decline ${pct(observedIntensityDecline)}%/yr; long-run energy-GDP elasticity ${observedElasticity.toFixed(2)}`);
p(`- Model structure at observed GDP growth: final energy ≈ ${pct(obsCagr - MODEL_INTENSITY_DECLINE)}%/yr`);
p(`  (${pct(MODEL_INTENSITY_DECLINE)}%/yr GDP-weighted intensity decline) vs ${pct(gTfc)}%/yr observed —`);
p('  the model over-predicts energy demand growth at high GDP growth.');
p();
p('At moderate GDP growth (~2%/yr) the two decompositions nearly agree');
p('(model: ~0.7%/yr energy growth; observed-elasticity view: ~0.8%/yr), so');
p('the unit-elasticity-minus-decline structure is adequate for the');
p('forward range but conservative-to-loose at the extremes: it would');
p('overstate energy demand in a fast-growth world (understating intensity');
p('improvements that historically accompanied growth) and understate the');
p('floor in a stagnant one. Worth revisiting only if forward GDP growth');
p('moves outside ~1-3%/yr.');
p();

p('## Forward contrast: the same engine 2025-2050');
p();
const y25 = f(2025), y50 = f(2050);
const gK = cagr(y25.capitalStock, y50.capitalStock, 25);
const gE = cagr(fwdE(y25), fwdE(y50), 25);
const gY = cagr(y25.gdp, y50.gdp, 25);
const elObs = def.series.electricity;
const neObs = def.series.nonElectric;
const gEhist = cagr(exergyE(elObs[0], neObs[0]), exergyE(elObs[N - 1], neObs[N - 1]), N - 1);
p('| | 1990-2025 (observed inputs) | 2025-2050 (model forward) |');
p('|---|---:|---:|');
p(`| Capital growth | ${pct(cagr(def.series.capital[0], def.series.capital[N - 1], N - 1))}%/yr | ${pct(gK)}%/yr |`);
p(`| Exergy-weighted E growth | ${pct(gEhist)}%/yr | ${pct(gE)}%/yr |`);
p(`| GDP growth | ${pct(obsCagr)}%/yr (obs) / ${pct(defCagr)}%/yr (model) | ${pct(gY)}%/yr |`);
p();
p('The forward slowdown that remains after calibration is input-driven —');
p('demographic savings decline (capital) and electrification shrinking');
p('final energy (E) — not a missing residual.');
p();

p('## Caveats');
p();
p('- Observed series are approximate (±5-10%); the pre-calibration');
p('  shortfall was several times that uncertainty.');
p('- Labor uses working-age headcount; education enters via collegeShare →');
p('  organizational efficiency, mirroring the model’s own separation.');
p('- Damages, energy-burden, food stress, and system overheads are zeroed');
p('  on both sides of the comparison (small, roughly constant shares).');
p('- 2020 covid dip is in the observed GDP series; per-decade rows bracket');
p('  it, and the 2020-2025 row is inflated by the rebound.');

writeFileSync('scripts/growth-backcast.md', lines.join('\n') + '\n');
console.log(lines.join('\n'));
console.log('\nReport written to scripts/growth-backcast.md');
